#!/usr/bin/env bash
# debugging, note that nginx service is running on port 80. init command says serice not running if true
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
